"""
Cephalon Agent

Warframe AI agent with four deterministic weapon tools:

- get_weapon
    Exact canonical data, description, mechanics and alternate-fire records.
- get_weapon_profile
    Relative strengths / weaknesses of one exact weapon.
- compare_weapons
    Side-by-side comparison of 2+ exact weapons on common metrics.
- search_weapons
    Discover weapons from broad category + relative statistical criteria.

The canonical database remains the source of truth. This module does not
calculate population percentiles or invent weapon ratings; it only organizes
metadata already generated by weapon_database.py for tool-friendly use.
"""

from __future__ import annotations

import argparse
import difflib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    from llama_cpp import Llama
except ImportError:  # Allows deterministic tool tests without loading llama-cpp.
    Llama = None  # type: ignore[assignment]


# ============================================================
# CONFIGURATION
# ============================================================

DATABASE_PATH = Path("data/normalized/weapons.json")

MODEL_PATH = Path(
    "models/Qwen2.5-3B-Instruct-Q4_K_M.gguf"
)

DEFAULT_N_CTX = 4096
DEFAULT_THREADS = 4
DEFAULT_GPU_LAYERS = 0


SYSTEM_PROMPT = """
You are a Cephalon knowledgeable about Warframe.

You are analytical, concise, and slightly theatrical, like a Warframe Cephalon.
Answer in the same language used by the user.

The local weapon database is the source of truth for weapon facts.
Use the single most appropriate weapon tool whenever possible.

Tool routing:
- get_weapon: one named weapon; exact stats, official description, mechanics,
  firing modes, alternate fire, damage composition, or other canonical facts.
- get_weapon_profile: one named weapon; relative strengths, weaknesses, best
  attributes, worst attributes, or what statistically stands out.
- compare_weapons: two or more named weapons; compare them using the same
  available statistical metrics.
- search_weapons: discover candidate weapons when the user is asking for
  weapons matching properties rather than asking about one exact named weapon.

Do not use get_weapon_profile for detailed mechanics or alternate-fire behavior.
Do not use search_weapons when the user already asks about one exact weapon.
Do not use multiple tools when one tool already answers the question.

Treat tool results as verified data. Do not invent statistics, mechanics,
effects, weapon classes, or properties not supported by the result.

If an exact weapon is not found, do not silently guess. Use the returned
suggestions or explain that the name was not found.

If the database lacks the information needed to answer, say so clearly.
If the user's request is internally incoherent or too ambiguous for the
available tools, ask for the missing clarification instead of fabricating an
answer.
""".strip()


# ============================================================
# METRIC VIEW
# ============================================================

LOW_BANDS = {
    "low",
    "very_low",
    "exceptionally_low",
}

HIGH_BANDS = {
    "high",
    "very_high",
    "exceptionally_high",
}


@dataclass(frozen=True)
class MetricView:
    """How to read one population-evaluated metric from weapons.json."""

    key: str
    paths: tuple[tuple[str, ...], ...]
    value_keys: tuple[str, ...]
    unit: str
    higher_is_better: bool


PROFILE_METRICS: tuple[MetricView, ...] = (
    MetricView(
        "damage",
        (
            ("damage", "base_multishot_damage"),
            ("damage", "base_damage"),
        ),
        ("damage", "total"),
        "damage",
        True,
    ),
    MetricView(
        "critical_chance",
        (("critical", "chance"),),
        ("percent",),
        "percent",
        True,
    ),
    MetricView(
        "critical_multiplier",
        (("critical", "multiplier"),),
        ("times",),
        "times",
        True,
    ),
    MetricView(
        "status_chance",
        (("status", "chance"),),
        ("percent",),
        "percent",
        True,
    ),
    MetricView(
        "fire_rate",
        (("handling", "fire_rate"),),
        ("per_second",),
        "per_second",
        True,
    ),
    MetricView(
        "magazine",
        (("handling", "magazine"),),
        ("rounds",),
        "rounds",
        True,
    ),
    MetricView(
        "reload",
        (("handling", "reload"),),
        ("seconds",),
        "seconds",
        False,
    ),
    MetricView(
        "attack_speed",
        (("handling", "attack_speed"),),
        ("attacks_per_second",),
        "attacks_per_second",
        True,
    ),
    MetricView(
        "range",
        (("handling", "range"),),
        ("meters",),
        "meters",
        True,
    ),
    MetricView(
        "follow_through",
        (("handling", "follow_through"),),
        ("coefficient",),
        "coefficient",
        True,
    ),
    MetricView(
        "combo_duration",
        (("handling", "combo_duration"),),
        ("seconds",),
        "seconds",
        True,
    ),
    MetricView(
        "heavy_attack_damage",
        (("handling", "heavy_attack"),),
        ("damage",),
        "damage",
        True,
    ),
    MetricView(
        "heavy_windup",
        (("handling", "heavy_windup"),),
        ("seconds",),
        "seconds",
        False,
    ),
)

METRIC_BY_KEY = {
    metric.key: metric
    for metric in PROFILE_METRICS
}


# Search criteria intentionally mirror concepts already exposed by the v2.5
# database. The second tuple member is the NUMERICAL percentile direction
# required for a match, not a general build recommendation.
SEARCH_CRITERIA: dict[str, tuple[str, str]] = {
    "high_damage": ("damage", "high"),
    "low_damage": ("damage", "low"),
    "high_critical_chance": ("critical_chance", "high"),
    "low_critical_chance": ("critical_chance", "low"),
    "high_critical_multiplier": ("critical_multiplier", "high"),
    "low_critical_multiplier": ("critical_multiplier", "low"),
    "high_status_chance": ("status_chance", "high"),
    "low_status_chance": ("status_chance", "low"),
    "fast_fire_rate": ("fire_rate", "high"),
    "slow_fire_rate": ("fire_rate", "low"),
    "large_magazine": ("magazine", "high"),
    "small_magazine": ("magazine", "low"),
    "fast_reload": ("reload", "low"),
    "slow_reload": ("reload", "high"),
    "fast_attack_speed": ("attack_speed", "high"),
    "slow_attack_speed": ("attack_speed", "low"),
    "long_range": ("range", "high"),
    "short_range": ("range", "low"),
    "high_follow_through": ("follow_through", "high"),
    "low_follow_through": ("follow_through", "low"),
    "long_combo_duration": ("combo_duration", "high"),
    "short_combo_duration": ("combo_duration", "low"),
    "high_heavy_attack_damage": ("heavy_attack_damage", "high"),
    "low_heavy_attack_damage": ("heavy_attack_damage", "low"),
    "fast_heavy_windup": ("heavy_windup", "low"),
    "slow_heavy_windup": ("heavy_windup", "high"),
}

SEARCH_CRITERION_NAMES = sorted(SEARCH_CRITERIA)


# ============================================================
# HELPERS
# ============================================================


def normalize_name(value: str) -> str:
    """Normalize a weapon name for deterministic lookup."""

    return " ".join(
        value.casefold().strip().split()
    )



def nested_dict(
    data: dict[str, Any],
    path: tuple[str, ...],
) -> dict[str, Any] | None:
    """Return a nested dictionary when every path component exists."""

    current: Any = data

    for key in path:
        if not isinstance(current, dict):
            return None
        current = current.get(key)

    if isinstance(current, dict):
        return current

    return None



def metric_snapshot(
    weapon: dict[str, Any],
    metric: MetricView,
) -> dict[str, Any] | None:
    """
    Read one tool-friendly metric from the canonical database.

    A metric is useful to profile/compare/search only when the database already
    contains population metadata for it. No percentile is calculated here.
    """

    stat: dict[str, Any] | None = None

    for path in metric.paths:
        candidate = nested_dict(
            weapon,
            path,
        )

        if (
            candidate is not None
            and isinstance(
                candidate.get("population_percentile"),
                (int, float),
            )
        ):
            stat = candidate
            break

    if stat is None:
        return None

    value: Any = None

    for value_key in metric.value_keys:
        if value_key in stat:
            value = stat.get(value_key)
            break

    return {
        "metric": metric.key,
        "value": value,
        "unit": metric.unit,
        "population_percentile": stat.get(
            "population_percentile"
        ),
        "relative_band": stat.get(
            "relative_band"
        ),
        "guide_tag": stat.get(
            "guide_tag"
        ),
        "relative_context": stat.get(
            "relative_context"
        ),
    }



def weapon_metric_map(
    weapon: dict[str, Any],
) -> dict[str, dict[str, Any]]:
    """Return all population-evaluated metrics available for one weapon."""

    metrics: dict[str, dict[str, Any]] = {}

    for definition in PROFILE_METRICS:
        snapshot = metric_snapshot(
            weapon,
            definition,
        )

        if snapshot is not None:
            metrics[definition.key] = snapshot

    return metrics



def metric_desirability_score(
    snapshot: dict[str, Any],
    definition: MetricView,
) -> float | None:
    """
    Convert percentile direction into a sorting score for profile presentation.

    This does NOT claim overall weapon quality. It only lets a deterministic
    profile put statistically favorable extremes before weaker ones.
    """

    percentile = snapshot.get(
        "population_percentile"
    )

    if not isinstance(percentile, (int, float)):
        return None

    if definition.higher_is_better:
        return float(percentile)

    return 100.0 - float(percentile)



def profile_bucket(
    snapshot: dict[str, Any],
    definition: MetricView,
) -> str:
    """Classify one relative metric as strength, weakness, or typical."""

    band = snapshot.get("relative_band")

    if band == "middle_range":
        return "typical"

    if band in HIGH_BANDS:
        return (
            "strength"
            if definition.higher_is_better
            else "weakness"
        )

    if band in LOW_BANDS:
        return (
            "weakness"
            if definition.higher_is_better
            else "strength"
        )

    return "typical"



def criterion_matches(
    snapshot: dict[str, Any],
    numerical_direction: str,
) -> bool:
    band = snapshot.get("relative_band")

    if numerical_direction == "high":
        return band in HIGH_BANDS

    if numerical_direction == "low":
        return band in LOW_BANDS

    return False



def criterion_score(
    snapshot: dict[str, Any],
    numerical_direction: str,
) -> float:
    percentile = snapshot.get(
        "population_percentile"
    )

    if not isinstance(percentile, (int, float)):
        return 0.0

    if numerical_direction == "high":
        return float(percentile)

    return 100.0 - float(percentile)


# ============================================================
# DATABASE
# ============================================================


class WeaponDatabase:
    """
    Load weapons.json and create an in-memory name index.

    With ~654 canonical weapons this intentionally remains simple. No vector
    database or persistent search index is necessary for the current scope.
    """

    def __init__(self, path: Path = DATABASE_PATH):
        self.path = path

        if not self.path.exists():
            raise FileNotFoundError(
                f"Weapon database not found: {self.path}"
            )

        with self.path.open(
            "r",
            encoding="utf-8",
        ) as file:
            payload = json.load(file)

        self.schema_version = (
            payload.get("schema_version")
            if isinstance(payload, dict)
            else None
        )

        self.weapons = self._extract_weapons(payload)

        if not self.weapons:
            raise ValueError(
                "The weapon database contains no usable weapons."
            )

        self.index: dict[str, dict[str, Any]] = {}

        for weapon in self.weapons:
            name = self._weapon_name(weapon)

            if not isinstance(name, str):
                continue

            key = normalize_name(name)

            if key:
                self.index[key] = weapon

        if not self.index:
            raise ValueError(
                "Could not create the weapon name index."
            )

    @staticmethod
    def _weapon_name(
        weapon: dict[str, Any],
    ) -> str | None:
        identity = weapon.get("identity")

        if isinstance(identity, dict):
            name = identity.get("name")

            if isinstance(name, str):
                return name

        name = weapon.get("name")

        if isinstance(name, str):
            return name

        return None

    @staticmethod
    def _extract_weapons(
        payload: Any,
    ) -> list[dict[str, Any]]:
        if isinstance(payload, list):
            return [
                item
                for item in payload
                if isinstance(item, dict)
            ]

        if isinstance(payload, dict):
            weapons = payload.get("weapons")

            if isinstance(weapons, dict):
                return [
                    weapon
                    for weapon in weapons.values()
                    if isinstance(weapon, dict)
                ]

            if isinstance(weapons, list):
                return [
                    weapon
                    for weapon in weapons
                    if isinstance(weapon, dict)
                ]

        raise ValueError(
            "Unsupported weapons.json structure."
        )

    def _not_found(
        self,
        weapon_name: str,
    ) -> dict[str, Any]:
        query = normalize_name(weapon_name)

        matches = difflib.get_close_matches(
            query,
            list(self.index.keys()),
            n=5,
            cutoff=0.55,
        )

        suggestions = [
            self._weapon_name(self.index[key])
            for key in matches
        ]

        return {
            "found": False,
            "query": weapon_name,
            "suggestions": suggestions,
        }

    def _exact_weapon(
        self,
        weapon_name: str,
    ) -> dict[str, Any] | None:
        return self.index.get(
            normalize_name(weapon_name)
        )

    # --------------------------------------------------------
    # TOOL 1 — exact canonical weapon
    # --------------------------------------------------------

    def get_weapon(
        self,
        weapon_name: str,
    ) -> dict[str, Any]:
        weapon = self._exact_weapon(
            weapon_name
        )

        if weapon is None:
            return self._not_found(
                weapon_name
            )

        return {
            "found": True,
            "query": weapon_name,
            "weapon": weapon,
        }

    # --------------------------------------------------------
    # TOOL 2 — relative profile
    # --------------------------------------------------------

    def get_weapon_profile(
        self,
        weapon_name: str,
    ) -> dict[str, Any]:
        weapon = self._exact_weapon(
            weapon_name
        )

        if weapon is None:
            return self._not_found(
                weapon_name
            )

        name = self._weapon_name(weapon)
        metrics = weapon_metric_map(weapon)

        strengths: list[dict[str, Any]] = []
        weaknesses: list[dict[str, Any]] = []
        typical: list[dict[str, Any]] = []

        for metric_key, snapshot in metrics.items():
            definition = METRIC_BY_KEY[
                metric_key
            ]

            item = dict(snapshot)
            score = metric_desirability_score(
                snapshot,
                definition,
            )

            if score is not None:
                item["relative_score"] = round(
                    score,
                    2,
                )

            bucket = profile_bucket(
                snapshot,
                definition,
            )

            if bucket == "strength":
                strengths.append(item)
            elif bucket == "weakness":
                weaknesses.append(item)
            else:
                typical.append(item)

        strengths.sort(
            key=lambda item: item.get(
                "relative_score",
                0,
            ),
            reverse=True,
        )

        weaknesses.sort(
            key=lambda item: item.get(
                "relative_score",
                100,
            )
        )

        classification = weapon.get(
            "classification",
            {},
        )

        return {
            "found": True,
            "query": weapon_name,
            "weapon": name,
            "category": (
                classification.get("category")
                if isinstance(classification, dict)
                else None
            ),
            "population": weapon.get("population"),
            "strengths": strengths,
            "weaknesses": weaknesses,
            "typical": typical,
            "note": (
                "Strengths and weaknesses are relative statistical "
                "extremes inside the weapon population, not a build "
                "recommendation or overall weapon rating."
            ),
        }

    # --------------------------------------------------------
    # TOOL 3 — compare exact weapons
    # --------------------------------------------------------

    def compare_weapons(
        self,
        weapon_names: list[str],
    ) -> dict[str, Any]:
        cleaned_names = [
            name.strip()
            for name in weapon_names
            if isinstance(name, str)
            and name.strip()
        ]

        if len(cleaned_names) < 2:
            return {
                "error": (
                    "compare_weapons requires at least two "
                    "weapon names."
                )
            }

        found: list[
            tuple[str, dict[str, Any]]
        ] = []
        missing: list[dict[str, Any]] = []

        for requested_name in cleaned_names:
            weapon = self._exact_weapon(
                requested_name
            )

            if weapon is None:
                missing.append(
                    self._not_found(
                        requested_name
                    )
                )
                continue

            canonical_name = (
                self._weapon_name(weapon)
                or requested_name
            )

            found.append(
                (canonical_name, weapon)
            )

        if len(found) < 2:
            return {
                "found": False,
                "requested": cleaned_names,
                "missing": missing,
                "error": (
                    "Fewer than two requested weapons were "
                    "found exactly."
                ),
            }

        metric_maps = {
            name: weapon_metric_map(weapon)
            for name, weapon in found
        }

        common_metrics = set.intersection(
            *(
                set(metrics)
                for metrics in metric_maps.values()
            )
        )

        comparison: dict[
            str,
            list[dict[str, Any]],
        ] = {}

        for metric_key in sorted(common_metrics):
            rows: list[dict[str, Any]] = []

            for weapon_name, _weapon in found:
                snapshot = metric_maps[
                    weapon_name
                ][metric_key]

                rows.append(
                    {
                        "weapon": weapon_name,
                        **snapshot,
                    }
                )

            comparison[metric_key] = rows

        return {
            "found": True,
            "requested": cleaned_names,
            "weapons_compared": [
                name
                for name, _weapon in found
            ],
            "missing": missing,
            "common_metrics": sorted(
                common_metrics
            ),
            "comparison": comparison,
            "note": (
                "Only population-evaluated metrics shared by all "
                "found weapons are compared."
            ),
        }

    # --------------------------------------------------------
    # TOOL 4 — deterministic discovery
    # --------------------------------------------------------

    def search_weapons(
        self,
        *,
        criteria: list[str],
        category: str | None = None,
        limit: int = 10,
    ) -> dict[str, Any]:
        clean_criteria = []

        for criterion in criteria:
            if (
                isinstance(criterion, str)
                and criterion in SEARCH_CRITERIA
                and criterion not in clean_criteria
            ):
                clean_criteria.append(
                    criterion
                )

        if not clean_criteria:
            return {
                "error": (
                    "search_weapons requires at least one supported "
                    "statistical criterion."
                ),
                "supported_criteria": SEARCH_CRITERION_NAMES,
            }

        if category == "any":
            category = None

        allowed_categories = {
            None,
            "primary",
            "secondary",
            "melee",
        }

        if category not in allowed_categories:
            return {
                "error": (
                    "Unsupported category. Use primary, secondary, "
                    "melee, or any."
                )
            }

        limit = max(
            1,
            min(int(limit), 20),
        )

        results: list[dict[str, Any]] = []

        for weapon in self.weapons:
            classification = weapon.get(
                "classification",
                {},
            )

            weapon_category = (
                classification.get("category")
                if isinstance(classification, dict)
                else None
            )

            if (
                category is not None
                and weapon_category != category
            ):
                continue

            metrics = weapon_metric_map(
                weapon
            )

            matched: list[dict[str, Any]] = []
            scores: list[float] = []
            failed = False

            for criterion in clean_criteria:
                (
                    metric_key,
                    numerical_direction,
                ) = SEARCH_CRITERIA[
                    criterion
                ]

                snapshot = metrics.get(
                    metric_key
                )

                if (
                    snapshot is None
                    or not criterion_matches(
                        snapshot,
                        numerical_direction,
                    )
                ):
                    failed = True
                    break

                matched.append(
                    {
                        "criterion": criterion,
                        **snapshot,
                    }
                )

                scores.append(
                    criterion_score(
                        snapshot,
                        numerical_direction,
                    )
                )

            if failed:
                continue

            name = self._weapon_name(
                weapon
            )

            if not isinstance(name, str):
                continue

            score = (
                sum(scores) / len(scores)
                if scores
                else 0.0
            )

            results.append(
                {
                    "weapon": name,
                    "category": weapon_category,
                    "match_score": round(
                        score,
                        2,
                    ),
                    "matched_criteria": matched,
                }
            )

        results.sort(
            key=lambda item: (
                -float(item["match_score"]),
                str(item["weapon"]).casefold(),
            )
        )

        return {
            "found": bool(results),
            "category": category or "any",
            "criteria": clean_criteria,
            "result_count": min(
                len(results),
                limit,
            ),
            "total_matches": len(results),
            "results": results[:limit],
            "note": (
                "Search uses canonical population bands only. "
                "The current database supports broad categories "
                "(primary/secondary/melee), not reliable firearm "
                "subtypes such as rifle versus shotgun."
            ),
        }

    def summary(self) -> dict[str, Any]:
        return {
            "database": str(self.path),
            "schema_version": self.schema_version,
            "weapons_loaded": len(self.weapons),
            "indexed_names": len(self.index),
            "tools": [
                "get_weapon",
                "get_weapon_profile",
                "compare_weapons",
                "search_weapons",
            ],
        }


# ============================================================
# TOOL DEFINITIONS
# ============================================================


TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_weapon",
            "description": (
                "Get verified canonical information for ONE exact named "
                "Warframe weapon. Use for exact statistics, damage types, "
                "official description, mechanics, firing modes, alternate "
                "fire, or other factual details. Do NOT use for relative "
                "strengths/weaknesses, comparing multiple weapons, or "
                "discovering weapons from desired attributes."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "weapon_name": {
                        "type": "string",
                        "description": (
                            "Exact weapon name, for example 'Soma Prime'."
                        ),
                    }
                },
                "required": ["weapon_name"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_weapon_profile",
            "description": (
                "Get the relative statistical profile of ONE exact named "
                "weapon. Use when the user asks for strengths, weaknesses, "
                "best attributes, worst attributes, or what statistically "
                "stands out compared with weapons of the same population. "
                "Do NOT use for detailed mechanics, alternate fire, or "
                "damage composition."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "weapon_name": {
                        "type": "string",
                        "description": (
                            "Exact weapon name, for example 'Hek'."
                        ),
                    }
                },
                "required": ["weapon_name"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "compare_weapons",
            "description": (
                "Compare TWO OR MORE exact named Warframe weapons using the "
                "same population-evaluated metrics. Use when the user names "
                "multiple weapons and asks which has more critical chance, "
                "damage, status, fire rate, magazine, reload, melee stats, "
                "or asks for an overall statistical comparison. Do NOT use "
                "to discover unnamed weapons."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "weapon_names": {
                        "type": "array",
                        "items": {"type": "string"},
                        "minItems": 2,
                        "maxItems": 6,
                        "description": (
                            "Exact weapon names to compare, for example "
                            "['Hek', 'Soma Prime']."
                        ),
                    }
                },
                "required": ["weapon_names"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "search_weapons",
            "description": (
                "Discover candidate weapons from relative statistical "
                "properties when the user is NOT asking about one exact "
                "named weapon. Example: 'what primary weapons have high "
                "critical chance and a large magazine?'. Use category plus "
                "one or more supported criteria. Do NOT use for exact weapon "
                "facts or direct comparison of already named weapons."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "category": {
                        "type": "string",
                        "enum": [
                            "primary",
                            "secondary",
                            "melee",
                            "any",
                        ],
                        "description": (
                            "Broad canonical weapon category. Use 'any' if "
                            "the user does not constrain the category."
                        ),
                    },
                    "criteria": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "enum": SEARCH_CRITERION_NAMES,
                        },
                        "minItems": 1,
                        "maxItems": 5,
                        "description": (
                            "Relative statistical properties requested by "
                            "the user. For example: "
                            "['high_critical_chance', 'large_magazine']."
                        ),
                    },
                    "limit": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 20,
                        "description": (
                            "Maximum number of candidates to return. Default 10."
                        ),
                    },
                },
                "required": ["criteria"],
                "additionalProperties": False,
            },
        },
    },
]


# ============================================================
# TOOL EXECUTION
# ============================================================



def parse_tool_arguments(
    raw_arguments: Any,
) -> dict[str, Any]:
    if isinstance(raw_arguments, dict):
        return raw_arguments

    if not isinstance(raw_arguments, str):
        raise ValueError(
            "Tool arguments must be JSON."
        )

    try:
        value = json.loads(raw_arguments)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Invalid tool arguments: {raw_arguments}"
        ) from exc

    if not isinstance(value, dict):
        raise ValueError(
            "Tool arguments must decode to an object."
        )

    return value



def execute_tool(
    database: WeaponDatabase,
    tool_name: str,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    if tool_name == "get_weapon":
        weapon_name = arguments.get(
            "weapon_name"
        )

        if not isinstance(weapon_name, str):
            return {
                "error": (
                    "get_weapon requires a string 'weapon_name'."
                )
            }

        return database.get_weapon(
            weapon_name
        )

    if tool_name == "get_weapon_profile":
        weapon_name = arguments.get(
            "weapon_name"
        )

        if not isinstance(weapon_name, str):
            return {
                "error": (
                    "get_weapon_profile requires a string "
                    "'weapon_name'."
                )
            }

        return database.get_weapon_profile(
            weapon_name
        )

    if tool_name == "compare_weapons":
        weapon_names = arguments.get(
            "weapon_names"
        )

        if not isinstance(weapon_names, list):
            return {
                "error": (
                    "compare_weapons requires an array "
                    "'weapon_names'."
                )
            }

        if not all(
            isinstance(name, str)
            for name in weapon_names
        ):
            return {
                "error": (
                    "Every compare_weapons weapon name must be a string."
                )
            }

        return database.compare_weapons(
            weapon_names
        )

    if tool_name == "search_weapons":
        criteria = arguments.get(
            "criteria"
        )

        if not isinstance(criteria, list):
            return {
                "error": (
                    "search_weapons requires an array 'criteria'."
                )
            }

        category = arguments.get(
            "category"
        )

        if category is not None and not isinstance(
            category,
            str,
        ):
            return {
                "error": (
                    "search_weapons 'category' must be a string."
                )
            }

        limit = arguments.get(
            "limit",
            10,
        )

        if not isinstance(limit, int):
            return {
                "error": (
                    "search_weapons 'limit' must be an integer."
                )
            }

        return database.search_weapons(
            criteria=criteria,
            category=category,
            limit=limit,
        )

    return {
        "error": f"Unknown tool: {tool_name}"
    }


# ============================================================
# CEPHALON AGENT
# ============================================================


class CephalonAgent:

    def __init__(
        self,
        database: WeaponDatabase,
        model_path: Path = MODEL_PATH,
        n_ctx: int = DEFAULT_N_CTX,
        n_threads: int = DEFAULT_THREADS,
        n_gpu_layers: int = DEFAULT_GPU_LAYERS,
        debug: bool = False,
    ):
        if Llama is None:
            raise ImportError(
                "llama-cpp-python is required to run the Cephalon model."
            )

        if not model_path.exists():
            raise FileNotFoundError(
                f"Model not found: {model_path}"
            )

        self.database = database
        self.debug = debug

        self.llm = Llama(
            model_path=str(model_path),
            n_ctx=n_ctx,
            n_threads=n_threads,
            n_gpu_layers=n_gpu_layers,
            chat_format="chatml-function-calling",
            verbose=False,
        )

    def ask(
        self,
        user_message: str,
    ) -> str:
        """
        Two-phase tool workflow.

        Phase 1:
            Qwen chooses among the four tools, or answers directly when no
            database lookup is needed.

        Phase 2:
            Requested deterministic tool calls are executed. Tools are then
            disabled and the model answers from the verified results.

        Keeping phase 2 tool-free prevents the recursive tool loop observed
        with the generic ChatML function-calling adapter.
        """

        messages: list[dict[str, Any]] = [
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": user_message,
            },
        ]

        response = self.llm.create_chat_completion(
            messages=messages,
            tools=TOOLS,
            tool_choice="auto",
            temperature=0.1,
            max_tokens=320,
        )

        message = response["choices"][0]["message"]

        tool_calls = (
            message.get("tool_calls")
            or []
        )

        if not tool_calls:
            content = message.get("content")

            if content:
                return content.strip()

            return (
                "The model returned neither a tool call nor a response."
            )

        retrieved_results: list[
            dict[str, Any]
        ] = []

        for tool_call in tool_calls:
            function = tool_call.get(
                "function",
                {},
            )

            tool_name = function.get(
                "name",
                "",
            )

            raw_arguments = function.get(
                "arguments",
                "{}",
            )

            try:
                arguments = parse_tool_arguments(
                    raw_arguments
                )

                if self.debug:
                    print(
                        "\n[CEPHALON TOOL CALL]"
                    )
                    print(
                        json.dumps(
                            {
                                "tool": tool_name,
                                "arguments": arguments,
                            },
                            indent=2,
                            ensure_ascii=False,
                        )
                    )

                result = execute_tool(
                    database=self.database,
                    tool_name=tool_name,
                    arguments=arguments,
                )

            except Exception as exc:
                arguments = {}
                result = {
                    "error": str(exc)
                }

            if self.debug:
                print("\n[TOOL RESULT]")
                print(
                    json.dumps(
                        result,
                        indent=2,
                        ensure_ascii=False,
                    )
                )

            retrieved_results.append(
                {
                    "tool": tool_name,
                    "arguments": arguments,
                    "result": result,
                }
            )

        tool_payload = json.dumps(
            retrieved_results,
            ensure_ascii=False,
        )

        final_system_prompt = (
            SYSTEM_PROMPT
            + "\n\n"
            + "Verified local database tool calls have already been "
              "completed for this turn. No tools are available during "
              "this phase. Answer the user's original question using only "
              "the retrieved information below. If the result is missing, "
              "ambiguous, empty, or insufficient, say that clearly instead "
              "of filling the gap with invented information."
        )

        final_messages: list[
            dict[str, Any]
        ] = [
            {
                "role": "system",
                "content": final_system_prompt,
            },
            {
                "role": "user",
                "content": user_message,
            },
            {
                "role": "user",
                "content": (
                    "Verified database result:\n"
                    "<tool_response>\n"
                    + tool_payload
                    + "\n</tool_response>\n\n"
                    "Now answer the original question."
                ),
            },
        ]

        final_response = self.llm.create_chat_completion(
            messages=final_messages,
            tools=None,
            tool_choice="none",
            temperature=0.1,
            max_tokens=640,
        )

        final_message = (
            final_response["choices"][0]["message"]
        )

        content = final_message.get(
            "content"
        )

        if content:
            return content.strip()

        return (
            "The model received the database result but produced no final answer."
        )


# ============================================================
# CLI
# ============================================================



def print_json(value: Any) -> None:
    print(
        json.dumps(
            value,
            indent=2,
            ensure_ascii=False,
        )
    )



def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Warframe Cephalon with deterministic weapon tools."
        )
    )

    parser.add_argument(
        "--database",
        type=Path,
        default=DATABASE_PATH,
    )

    parser.add_argument(
        "--model",
        type=Path,
        default=MODEL_PATH,
    )

    parser.add_argument(
        "--n-ctx",
        type=int,
        default=DEFAULT_N_CTX,
    )

    parser.add_argument(
        "--threads",
        type=int,
        default=DEFAULT_THREADS,
    )

    parser.add_argument(
        "--gpu-layers",
        type=int,
        default=DEFAULT_GPU_LAYERS,
    )

    parser.add_argument(
        "--debug",
        action="store_true",
    )

    subparsers = parser.add_subparsers(
        dest="command",
        required=True,
    )

    # Backward-compatible direct get_weapon test.
    tool_parser = subparsers.add_parser(
        "tool",
        help="Directly test get_weapon without loading the language model.",
    )
    tool_parser.add_argument("weapon_name")

    profile_parser = subparsers.add_parser(
        "profile",
        help="Directly test get_weapon_profile.",
    )
    profile_parser.add_argument("weapon_name")

    compare_parser = subparsers.add_parser(
        "compare",
        help="Directly test compare_weapons.",
    )
    compare_parser.add_argument(
        "weapon_names",
        nargs="+",
    )

    search_parser = subparsers.add_parser(
        "search",
        help="Directly test search_weapons.",
    )
    search_parser.add_argument(
        "criteria",
        nargs="+",
        choices=SEARCH_CRITERION_NAMES,
    )
    search_parser.add_argument(
        "--category",
        choices=[
            "primary",
            "secondary",
            "melee",
            "any",
        ],
        default="any",
    )
    search_parser.add_argument(
        "--limit",
        type=int,
        default=10,
    )

    ask_parser = subparsers.add_parser(
        "ask",
        help="Ask the Cephalon a question.",
    )
    ask_parser.add_argument("message")

    subparsers.add_parser(
        "database",
        help="Show database/index/tool status.",
    )

    return parser



def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    database = WeaponDatabase(
        args.database
    )

    if args.command == "database":
        print_json(
            database.summary()
        )
        return

    if args.command == "tool":
        print_json(
            database.get_weapon(
                args.weapon_name
            )
        )
        return

    if args.command == "profile":
        print_json(
            database.get_weapon_profile(
                args.weapon_name
            )
        )
        return

    if args.command == "compare":
        print_json(
            database.compare_weapons(
                args.weapon_names
            )
        )
        return

    if args.command == "search":
        print_json(
            database.search_weapons(
                criteria=args.criteria,
                category=args.category,
                limit=args.limit,
            )
        )
        return

    if args.command == "ask":
        agent = CephalonAgent(
            database=database,
            model_path=args.model,
            n_ctx=args.n_ctx,
            n_threads=args.threads,
            n_gpu_layers=args.gpu_layers,
            debug=args.debug,
        )

        answer = agent.ask(
            args.message
        )

        print("\nCEPHALON")
        print("========")
        print(answer)
        return


if __name__ == "__main__":
    main()
