#Cephalon Agent


"""
Cephalon Agent

Warframe AI agent with four deterministic weapon tools:

- get_weapon
    Exact canonical data, description, mechanics and alternate-fire records.
- get_weapon_profile
    Relative strengths / weaknesses of one exact weapon.
- compare_weapons
    Side-by-side comparison of 2+ exact weapons on common metrics.
- search_weapons
    Discover weapons from broad category + relative statistical criteria.

The canonical database remains the source of truth. This module does not
calculate population percentiles or invent weapon ratings; it only organizes
metadata already generated by weapon_database.py for tool-friendly use.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

try:
    from llama_cpp import Llama
except ImportError:  # Allows deterministic tool tests without loading llama-cpp.
    Llama = None  # type: ignore[assignment]

from modules.weapon_views import (
    SEARCH_CRITERION_NAMES,
    WeaponViewDatabase,
)

from modules.warframe_localization import (
    SPANISH_LOCALIZATION_GUIDE,
    localize_tool_result,
)


# ============================================================
# CONFIGURATION
# ============================================================

DATABASE_PATH = Path("data/normalized/weapons.json")

MODEL_PATH = Path(
    "models/Qwen_Qwen3.5-4B-Q4_K_M.gguf"
)

DEFAULT_N_CTX = 4096
DEFAULT_THREADS = 4
DEFAULT_GPU_LAYERS = 0

MAX_TOOL_STEPS = 3


SYSTEM_PROMPT = """
You are a Cephalon knowledgeable about Warframe.

You are analytical, concise, and slightly theatrical.
Answer in the same language used by the user.

The local weapon database is the source of truth.
Use weapon tools when a database lookup is needed.
A single user request may use more than one tool sequentially when the
answer requires information from multiple stages, such as discovering
candidate weapons and then inspecting one exact weapon.

Tool routing:

- get_weapon:
  FACTS about ONE exact named weapon.
  Use for questions such as:
  "How much critical chance does Hek have?"
  "What is Hek's Riven disposition?"
  "How does Trumna fire?"
  "What damage types does this weapon have?"
  Use this for exact values, description, mechanics, firing modes,
  alternate fire, Riven data, damage composition, and handling facts.
  Do NOT use it for strengths/weaknesses or discovery.

- get_weapon_profile:
  RELATIVE PROFILE of ONE exact named weapon.
  Use ONLY when the user asks for strengths, weaknesses, best attributes,
  worst attributes, what stands out, or whether a stat is relatively
  high/low compared with similar weapons.
  Do NOT use this merely because the user asks for one exact stat value.

- compare_weapons:
  COMPARISON of TWO OR MORE exact named weapons.
  Use when the user explicitly names multiple weapons and wants their
  statistics compared.

- search_weapons:
  DISCOVERY of unnamed candidate weapons matching requested properties.
  Use when the user asks "what weapons", "which weapons", or asks for a
  category of weapons with desired traits such as high critical chance,
  large magazine, fast reload, etc.
  Never pass "any" as a weapon_name to get_weapon or get_weapon_profile.

Routing priority:
1. Multiple named weapons -> compare_weapons.
2. Unnamed candidates matching traits -> search_weapons.
3. One named weapon + explicit relative evaluation -> get_weapon_profile.
4. One named weapon + factual question -> get_weapon.

Treat tool results as verified data.
Do not invent statistics, mechanics, effects, popularity, rankings, or
properties not present in the result.

If an exact weapon is not found, do not silently guess.
If the result is insufficient, say so clearly.
""".strip()


SYSTEM_PROMPT = (
    SYSTEM_PROMPT
    + "\n\n"
    + SPANISH_LOCALIZATION_GUIDE
)


# ============================================================
# TOOL-SPECIFIC WEAPON VIEWS
# ============================================================

# Keep the historical class name used by the rest of this module.
# The implementation now loads compact prebuilt views from data/views.
WeaponDatabase = WeaponViewDatabase


# ============================================================
# TOOL DEFINITIONS
# ============================================================


TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_weapon",
            "description": (
                "FACT LOOKUP for ONE exact named Warframe weapon. "
                "Use for exact values and canonical facts: critical chance, "
                "critical multiplier, status, damage, multishot, fire rate, "
                "magazine, reload, Riven disposition, official description, "
                "trigger, mechanics, firing modes, alternate fire, and "
                "damage composition. Use this when the user asks how much "
                "of a stat one named weapon has. Do NOT use for strengths, "
                "weaknesses, best/worst attributes, comparisons, or discovery."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "weapon_name": {
                        "type": "string",
                        "description": (
                            "Exact named weapon, for example 'Hek' "
                            "or 'Soma Prime'. Never use 'any'."
                        ),
                    }
                },
                "required": [
                    "weapon_name"
                ],
                "additionalProperties":
                    False,
            },
        },
    },

    {
        "type": "function",
        "function": {
            "name":
                "get_weapon_profile",

            "description": (
                "RELATIVE PROFILE for ONE exact named weapon. "
                "Use ONLY for strengths, weaknesses, best attributes, "
                "worst attributes, what statistically stands out, or "
                "whether its stats are relatively high/low compared with "
                "similar weapons. Do NOT use for a simple exact-value "
                "question such as 'how much critical chance does Hek have?'."
            ),

            "parameters": {
                "type":
                    "object",

                "properties": {
                    "weapon_name": {
                        "type":
                            "string",

                        "description": (
                            "Exact named weapon, for example 'Hek'. "
                            "Never use 'any'."
                        ),
                    }
                },

                "required": [
                    "weapon_name"
                ],

                "additionalProperties":
                    False,
            },
        },
    },

    {
        "type": "function",
        "function": {
            "name":
                "compare_weapons",

            "description": (
                "Compare TWO OR MORE exact named Warframe weapons. "
                "Use only when multiple specific weapon names are supplied. "
                "Returns exact comparable values grouped by weapon. "
                "Do NOT use to discover unnamed candidates."
            ),

            "parameters": {
                "type":
                    "object",

                "properties": {
                    "weapon_names": {
                        "type":
                            "array",

                        "items": {
                            "type":
                                "string"
                        },

                        "minItems":
                            2,

                        "maxItems":
                            6,

                        "description": (
                            "Exact weapon names, for example "
                            "['Hek', 'Soma Prime']."
                        ),
                    }
                },

                "required": [
                    "weapon_names"
                ],

                "additionalProperties":
                    False,
            },
        },
    },

    {
        "type": "function",
        "function": {
            "name":
                "search_weapons",

            "description": (
                "DISCOVER unnamed candidate weapons that satisfy requested "
                "relative statistical traits. Use when the user asks what "
                "or which weapons match properties such as high critical "
                "chance, large magazine, fast reload, etc. This is the "
                "correct tool for requests like 'What primary weapons have "
                "high critical chance and a large magazine?'. Do NOT call "
                "get_weapon_profile with weapon_name='any'."
            ),

            "parameters": {
                "type":
                    "object",

                "properties": {
                    "category": {
                        "type":
                            "string",

                        "enum": [
                            "primary",
                            "secondary",
                            "melee",
                            "any",
                        ],

                        "description": (
                            "Broad weapon category. Use 'any' only here "
                            "when the user does not constrain category."
                        ),
                    },

                    "criteria": {
                        "type":
                            "array",

                        "items": {
                            "type":
                                "string",

                            "enum":
                                SEARCH_CRITERION_NAMES,
                        },

                        "minItems":
                            1,

                        "maxItems":
                            5,

                        "description": (
                            "Requested relative traits, for example "
                            "['high_critical_chance', 'large_magazine']."
                        ),
                    },

                    "limit": {
                        "type":
                            "integer",

                        "minimum":
                            1,

                        "maximum":
                            20,

                        "description": (
                            "Maximum number of candidates. Default 10."
                        ),
                    },
                },

                "required": [
                    "criteria"
                ],

                "additionalProperties":
                    False,
            },
        },
    },
]



# ============================================================
# TOOL EXECUTION
# ============================================================



def parse_qwen_tool_calls(
    content: Any,
) -> list[dict[str, Any]]:
    """
    Fallback for Qwen native XML-like tool calls.

    Normal OpenAI-style message["tool_calls"] always has priority.
    This parser runs only when llama-cpp-python leaves a native
    <tool_call> block inside message["content"].
    """

    if not isinstance(
        content,
        str,
    ):
        return []

    if "<tool_call>" not in content:
        return []

    call_pattern = re.compile(
        r"<tool_call>\s*"
        r"<function=([^>\s]+)>\s*"
        r"(.*?)"
        r"</function>\s*"
        r"</tool_call>",
        re.DOTALL,
    )

    parameter_pattern = re.compile(
        r"<parameter=([^>\s]+)>\s*"
        r"(.*?)"
        r"</parameter>",
        re.DOTALL,
    )

    tool_calls: list[
        dict[str, Any]
    ] = []

    for index, match in enumerate(
        call_pattern.finditer(
            content
        ),
        start=1,
    ):
        tool_name = (
            match.group(1).strip()
        )

        parameter_block = (
            match.group(2)
        )

        arguments: dict[
            str,
            Any,
        ] = {}

        for parameter_match in (
            parameter_pattern.finditer(
                parameter_block
            )
        ):
            key = (
                parameter_match
                .group(1)
                .strip()
            )

            raw_value = (
                parameter_match
                .group(2)
                .strip()
            )

            try:
                value = json.loads(
                    raw_value
                )

            except json.JSONDecodeError:
                value = raw_value

            arguments[
                key
            ] = value

        tool_calls.append(
            {
                "id":
                    f"qwen_native_{index}",

                "type":
                    "function",

                "function": {
                    "name":
                        tool_name,

                    "arguments":
                        json.dumps(
                            arguments,
                            ensure_ascii=False,
                        ),
                },
            }
        )

    return tool_calls


def clean_model_output(
    content: str,
) -> str:
    """
    Remove Qwen visible thinking trace before presenting
    the final response to the user.
    """
    if "</think>" in content:
        content = content.split(
            "</think>",
            1,
        )[1]

    return content.strip()


def parse_tool_arguments(
    raw_arguments: Any,
) -> dict[str, Any]:
    if isinstance(raw_arguments, dict):
        return raw_arguments

    if not isinstance(raw_arguments, str):
        raise ValueError(
            "Tool arguments must be JSON."
        )

    try:
        value = json.loads(raw_arguments)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Invalid tool arguments: {raw_arguments}"
        ) from exc

    if not isinstance(value, dict):
        raise ValueError(
            "Tool arguments must decode to an object."
        )

    return value



def execute_tool(
    database: WeaponDatabase,
    tool_name: str,
    arguments: dict[str, Any],
) -> dict[str, Any]:
    if tool_name == "get_weapon":
        weapon_name = arguments.get(
            "weapon_name"
        )

        if not isinstance(weapon_name, str):
            return {
                "error": (
                    "get_weapon requires a string 'weapon_name'."
                )
            }

        return database.get_weapon(
            weapon_name
        )

    if tool_name == "get_weapon_profile":
        weapon_name = arguments.get(
            "weapon_name"
        )

        if not isinstance(weapon_name, str):
            return {
                "error": (
                    "get_weapon_profile requires a string "
                    "'weapon_name'."
                )
            }

        return database.get_weapon_profile(
            weapon_name
        )

    if tool_name == "compare_weapons":
        weapon_names = arguments.get(
            "weapon_names"
        )

        if not isinstance(weapon_names, list):
            return {
                "error": (
                    "compare_weapons requires an array "
                    "'weapon_names'."
                )
            }

        if not all(
            isinstance(name, str)
            for name in weapon_names
        ):
            return {
                "error": (
                    "Every compare_weapons weapon name must be a string."
                )
            }

        return database.compare_weapons(
            weapon_names
        )

    if tool_name == "search_weapons":
        criteria = arguments.get(
            "criteria"
        )

        if not isinstance(criteria, list):
            return {
                "error": (
                    "search_weapons requires an array 'criteria'."
                )
            }

        category = arguments.get(
            "category"
        )

        if category is not None and not isinstance(
            category,
            str,
        ):
            return {
                "error": (
                    "search_weapons 'category' must be a string."
                )
            }

        limit = arguments.get(
            "limit",
            10,
        )

        if not isinstance(limit, int):
            return {
                "error": (
                    "search_weapons 'limit' must be an integer."
                )
            }

        return database.search_weapons(
            criteria=criteria,
            category=category,
            limit=limit,
        )

    return {
        "error": f"Unknown tool: {tool_name}"
    }


# ============================================================
# CEPHALON AGENT
# ============================================================


class CephalonAgent:

    def __init__(
        self,
        database: WeaponDatabase,
        model_path: Path = MODEL_PATH,
        n_ctx: int = DEFAULT_N_CTX,
        n_threads: int = DEFAULT_THREADS,
        n_gpu_layers: int = DEFAULT_GPU_LAYERS,
        debug: bool = False,
    ):
        if Llama is None:
            raise ImportError(
                "llama-cpp-python is required to run the Cephalon model."
            )

        if not model_path.exists():
            raise FileNotFoundError(
                f"Model not found: {model_path}"
            )

        self.database = database
        self.debug = debug

        self.llm = Llama(
            model_path=str(model_path),
            n_ctx=n_ctx,
            n_threads=n_threads,
            n_gpu_layers=n_gpu_layers,
            verbose=False,
        )

    def ask(
        self,
        user_message: str,
    ) -> str:
        """
        Bounded agentic tool loop.

        The model may:

        1. Answer directly.
        2. Call a deterministic weapon tool.
        3. Observe its result.
        4. Call another tool if the original request still requires
           additional information.
        5. Answer when enough verified information is available.

        Tool use is capped by MAX_TOOL_STEPS so the model cannot enter
        an unbounded tool loop.
        """

        messages: list[
            dict[str, Any]
        ] = [
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": user_message,
            },
        ]

        for step in range(
            1,
            MAX_TOOL_STEPS + 1,
        ):
            response = (
                self.llm.create_chat_completion(
                    messages=messages,
                    tools=TOOLS,
                    tool_choice="auto",
                    temperature=0.1,
                    max_tokens=640,
                )
            )

            message = (
                response["choices"][0]["message"]
            )

            content = message.get(
                "content"
            )

            tool_calls = (
                message.get("tool_calls")
                or []
            )

            fallback_used = False

            # Normal llama-cpp/OpenAI-style tool calls have priority.
            # Fall back to Qwen native XML-like calls only when needed.
            if not tool_calls:
                tool_calls = (
                    parse_qwen_tool_calls(
                        content
                    )
                )

                fallback_used = bool(
                    tool_calls
                )

                if (
                    fallback_used
                    and self.debug
                ):
                    print(
                        "\n[QWEN NATIVE TOOL CALL FALLBACK]"
                    )

            # No tool call means the model considers the task complete.
            if not tool_calls:
                if content:
                    return clean_model_output(
                        content
                    )

                return (
                    "The model returned neither "
                    "a tool call nor a response."
                )

            if self.debug:
                print(
                    f"\n[AGENT STEP {step}/{MAX_TOOL_STEPS}]"
                )

            normalized_tool_calls: list[
                dict[str, Any]
            ] = []

            # Guarantee stable IDs for tool-result association.
            for index, tool_call in enumerate(
                tool_calls,
                start=1,
            ):
                normalized_call = dict(
                    tool_call
                )

                if (
                    fallback_used
                    or not normalized_call.get(
                        "id"
                    )
                ):
                    normalized_call["id"] = (
                        f"cephalon_{step}_{index}"
                    )

                normalized_tool_calls.append(
                    normalized_call
                )

            # Store the assistant decision in conversation history.
            #
            # When the native-Qwen fallback was used, content already
            # contains the XML representation of the same tool call.
            # Do not duplicate that XML; preserve only the normalized
            # structured tool call.
            assistant_content = (
                ""
                if fallback_used
                else content
            )

            # Qwen3.5 native chat template expects
            # function.arguments to be a mapping, not a JSON string.
            # Keep normalized_tool_calls unchanged for execution,
            # but convert arguments before storing the assistant
            # tool call in conversation history.
            history_tool_calls: list[
                dict[str, Any]
            ] = []

            for tool_call in (
                normalized_tool_calls
            ):
                history_call = dict(
                    tool_call
                )

                history_function = dict(
                    history_call.get(
                        "function",
                        {},
                    )
                )

                raw_history_arguments = (
                    history_function.get(
                        "arguments",
                        {},
                    )
                )

                try:
                    history_arguments = (
                        parse_tool_arguments(
                            raw_history_arguments
                        )
                    )
                except ValueError:
                    history_arguments = {}

                history_function[
                    "arguments"
                ] = history_arguments

                history_call[
                    "function"
                ] = history_function

                history_tool_calls.append(
                    history_call
                )

            messages.append(
                {
                    "role": "assistant",
                    "content": assistant_content,
                    "tool_calls":
                        history_tool_calls,
                }
            )

            for tool_call in (
                normalized_tool_calls
            ):
                function = tool_call.get(
                    "function",
                    {},
                )

                tool_name = function.get(
                    "name",
                    "",
                )

                raw_arguments = function.get(
                    "arguments",
                    "{}",
                )

                try:
                    arguments = (
                        parse_tool_arguments(
                            raw_arguments
                        )
                    )

                    if self.debug:
                        print(
                            "\n[CEPHALON TOOL CALL]"
                        )
                        print(
                            json.dumps(
                                {
                                    "tool":
                                        tool_name,
                                    "arguments":
                                        arguments,
                                },
                                indent=2,
                                ensure_ascii=False,
                            )
                        )

                    result = execute_tool(
                        database=self.database,
                        tool_name=tool_name,
                        arguments=arguments,
                    )

                    result = localize_tool_result(
                        result
                    )

                except Exception as exc:
                    arguments = {}

                    result = {
                        "error": str(exc)
                    }

                if self.debug:
                    print(
                        "\n[TOOL RESULT]"
                    )
                    print(
                        json.dumps(
                            result,
                            indent=2,
                            ensure_ascii=False,
                        )
                    )

                messages.append(
                    {
                        "role": "tool",
                        "tool_call_id":
                            tool_call["id"],
                        "content":
                            json.dumps(
                                result,
                                ensure_ascii=False,
                            ),
                    }
                )

        # ----------------------------------------------------
        # Safety boundary:
        # after MAX_TOOL_STEPS, tools are disabled and the
        # model must answer using observations already gathered.
        # ----------------------------------------------------

        messages.append(
            {
                "role": "user",
                "content": (
                    "The tool-use limit has been reached. "
                    "Do not request another tool. "
                    "Answer the original question using only "
                    "the verified tool results already present "
                    "in the conversation."
                ),
            }
        )

        final_response = (
            self.llm.create_chat_completion(
                messages=messages,
                tools=None,
                tool_choice="none",
                temperature=0.1,
                max_tokens=640,
            )
        )

        final_message = (
            final_response[
                "choices"
            ][0]["message"]
        )

        content = final_message.get(
            "content"
        )

        if content:
            return clean_model_output(
                content
            )

        return (
            "The model reached the tool-use limit "
            "but produced no final answer."
        )


# ============================================================
# CLI
# ============================================================



def print_json(value: Any) -> None:
    print(
        json.dumps(
            value,
            indent=2,
            ensure_ascii=False,
        )
    )



def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Warframe Cephalon with deterministic weapon tools."
        )
    )

    parser.add_argument(
        "--database",
        type=Path,
        default=DATABASE_PATH,
    )

    parser.add_argument(
        "--model",
        type=Path,
        default=MODEL_PATH,
    )

    parser.add_argument(
        "--n-ctx",
        type=int,
        default=DEFAULT_N_CTX,
    )

    parser.add_argument(
        "--threads",
        type=int,
        default=DEFAULT_THREADS,
    )

    parser.add_argument(
        "--gpu-layers",
        type=int,
        default=DEFAULT_GPU_LAYERS,
    )

    parser.add_argument(
        "--debug",
        action="store_true",
    )

    subparsers = parser.add_subparsers(
        dest="command",
        required=True,
    )

    # Backward-compatible direct get_weapon test.
    tool_parser = subparsers.add_parser(
        "tool",
        help="Directly test get_weapon without loading the language model.",
    )
    tool_parser.add_argument("weapon_name")

    profile_parser = subparsers.add_parser(
        "profile",
        help="Directly test get_weapon_profile.",
    )
    profile_parser.add_argument("weapon_name")

    compare_parser = subparsers.add_parser(
        "compare",
        help="Directly test compare_weapons.",
    )
    compare_parser.add_argument(
        "weapon_names",
        nargs="+",
    )

    search_parser = subparsers.add_parser(
        "search",
        help="Directly test search_weapons.",
    )
    search_parser.add_argument(
        "criteria",
        nargs="+",
        choices=SEARCH_CRITERION_NAMES,
    )
    search_parser.add_argument(
        "--category",
        choices=[
            "primary",
            "secondary",
            "melee",
            "any",
        ],
        default="any",
    )
    search_parser.add_argument(
        "--limit",
        type=int,
        default=10,
    )

    ask_parser = subparsers.add_parser(
        "ask",
        help="Ask the Cephalon a question.",
    )
    ask_parser.add_argument("message")

    subparsers.add_parser(
        "database",
        help="Show database/index/tool status.",
    )

    return parser



def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    database = WeaponDatabase(
        args.database
    )

    if args.command == "database":
        print_json(
            database.summary()
        )
        return

    if args.command == "tool":
        print_json(
            database.get_weapon(
                args.weapon_name
            )
        )
        return

    if args.command == "profile":
        print_json(
            database.get_weapon_profile(
                args.weapon_name
            )
        )
        return

    if args.command == "compare":
        print_json(
            database.compare_weapons(
                args.weapon_names
            )
        )
        return

    if args.command == "search":
        print_json(
            database.search_weapons(
                criteria=args.criteria,
                category=args.category,
                limit=args.limit,
            )
        )
        return

    if args.command == "ask":
        agent = CephalonAgent(
            database=database,
            model_path=args.model,
            n_ctx=args.n_ctx,
            n_threads=args.threads,
            n_gpu_layers=args.gpu_layers,
            debug=args.debug,
        )

        answer = agent.ask(
            args.message
        )

        print("\nCEPHALON")
        print("========")
        print(answer)
        return


if __name__ == "__main__":
    main()
