# modules/weapon_pipeline.py

from __future__ import annotations

from collections.abc import Mapping
from functools import lru_cache
from typing import Any

from modules.knowledge import (
    load_knowledge_base,
    retrieve_knowledge,
)
from modules.prompt_builder import build_analysis_context
from modules.rule_engine import evaluate_rules
from modules.weapon_interpreter import interpret_weapon


@lru_cache(maxsize=1)
def get_knowledge_base() -> dict[str, Any]:
    """
    Cache the local knowledge base so JSON files are not reloaded per request.

    Call ``get_knowledge_base.cache_clear()`` during development after editing
    knowledge files.
    """
    return load_knowledge_base()


def _validate_normalized_weapon(
    weapon_data: Mapping[str, Any],
) -> dict[str, Any]:
    """
    Validate the minimum structure expected from the normalized database.

    This does not normalize or reinterpret source data. It only verifies that
    the selected entry resembles the schema generated by weapon_database.py.
    """
    if not isinstance(weapon_data, Mapping):
        raise TypeError(
            "weapon_data must be a Mapping."
        )

    required_sections = (
        "classification",
        "root_stats",
        "attack_modes",
    )

    missing_sections = [
        section
        for section in required_sections
        if section not in weapon_data
    ]

    if missing_sections:
        raise ValueError(
            "Normalized weapon data is missing required sections: "
            + ", ".join(missing_sections)
            + "."
        )

    classification = weapon_data.get(
        "classification"
    )
    root_stats = weapon_data.get(
        "root_stats"
    )
    attack_modes = weapon_data.get(
        "attack_modes"
    )

    if not isinstance(
        classification,
        Mapping,
    ):
        raise ValueError(
            "classification must be a Mapping."
        )

    if not isinstance(
        root_stats,
        Mapping,
    ):
        raise ValueError(
            "root_stats must be a Mapping."
        )

    if not isinstance(
        attack_modes,
        list,
    ):
        raise ValueError(
            "attack_modes must be a list."
        )

    if not attack_modes:
        raise ValueError(
            "attack_modes cannot be empty."
        )

    return dict(weapon_data)


def prepare_weapon_analysis(
    weapon_data: Mapping[str, Any],
) -> dict[str, Any]:
    """
    Execute every deterministic stage before prompting the language model.

    The input must already be normalized by ``weapon_database.py``.
    """
    normalized_weapon = _validate_normalized_weapon(
        weapon_data
    )

    interpretation = interpret_weapon(
        normalized_weapon
    )

    if not isinstance(
        interpretation,
        dict,
    ):
        raise TypeError(
            "The weapon interpreter must return a dictionary."
        )

    knowledge_base = get_knowledge_base()

    concept_ids = evaluate_rules(
        interpretation=interpretation,
        rules=knowledge_base["rules"],
    )

    retrieved_knowledge = retrieve_knowledge(
        concept_ids=concept_ids,
        concepts=knowledge_base["concepts"],
    )

    analysis_context = build_analysis_context(
        interpretation=interpretation,
        retrieved_knowledge=retrieved_knowledge,
    )

    return {
        "weapon_data": normalized_weapon,
        "interpretation": interpretation,
        "activated_concepts": concept_ids,
        "retrieved_knowledge": retrieved_knowledge,
        "analysis_context": analysis_context,
    }